/**
 * Cocktail HTML5 parser.
 * @see https://github.com/haxecocktail/cocktail-html-parser
 * 
 * Cocktail, HTML rendering engine
 * http://haxe.org/com/libs/cocktail
 *
 * Copyright (c) Silex Labs 2013 - 2014
 * Cocktail is available under the MIT license
 * http://www.silexlabs.org/labs/cocktail-licensing/
 */
package cocktail.parser.html;

enum Quotation
{
	DOUBLE_QUOTED;
	SINGLE_QUOTED;
	UNQUOTED;
}

/**
 * The states of the Tokenizer machine.
 */
enum State
{
	DATA;
	CHARACTER_REFERENCE_IN_DATA;
	RCDATA;
	CHARACTER_REFERENCE_IN_RCDATA;
	RAWTEXT;
	SCRIPT_DATA;
	PLAINTEXT;
	TAG_OPEN;
	END_TAG_OPEN;
	TAG_NAME;
	RCDATA_LESS_THAN_SIGN;
	RCDATA_END_TAG_OPEN;
	RCDATA_END_TAG_NAME;
	RAWTEXT_LESS_THAN_SIGN;
	RAWTEXT_END_TAG_OPEN;
	RAWTEXT_END_TAG_NAME;
	SCRIPT_DATA_LESS_THAN_SIGN;
	SCRIPT_DATA_END_TAG_OPEN;
	SCRIPT_DATA_END_TAG_NAME;
	SCRIPT_DATA_ESCAPE_START;
	SCRIPT_DATA_ESCAPE_START_DASH;
	SCRIPT_DATA_ESCAPED;
	SCRIPT_DATA_ESCAPED_DASH;
	SCRIPT_DATA_ESCAPED_DASH_DASH;
	SCRIPT_DATA_ESCAPED_LESS_THAN_SIGN;
	SCRIPT_DATA_ESCAPED_END_TAG_OPEN;
	SCRIPT_DATA_ESCAPED_END_TAG_NAME;
	SCRIPT_DATA_DOUBLE_ESCAPE_START;
	SCRIPT_DATA_DOUBLE_ESCAPED;
	SCRIPT_DATA_DOUBLE_ESCAPED_DASH;
	SCRIPT_DATA_DOUBLE_ESCAPED_DASH_DASH;
	SCRIPT_DATA_DOUBLE_ESCAPED_LESS_THAN_SIGN;
	SCRIPT_DATA_DOUBLE_ESCAPE_END;
	BEFORE_ATTRIBUTE_NAME;
	ATTRIBUTE_NAME;
	AFTER_ATTRIBUTE_NAME;
	BEFORE_ATTRIBUTE_VALUE;
	ATTRIBUTE_VALUE_STATE( q : Quotation ); // DOUBLE_QUOTED & SINGLE_QUOTED & UNQUOTED
	CHARACTER_REFERENCE_IN_ATTRIBUTE_VALUE( q : Quotation );
	AFTER_ATTRIBUTE_VALUE_QUOTED;
	SELF_CLOSING_START_TAG;
	BOGUS_COMMENT;
	MARKUP_DECLARATION_OPEN;
	COMMENT_START;
	COMMENT_START_DASH;
	COMMENT;
	COMMENT_END_DASH;
	COMMENT_END;
	COMMENT_END_BANG;
	DOCTYPE;
	BEFORE_DOCTYPE_NAME;
	DOCTYPE_NAME;
	AFTER_DOCTYPE_NAME;
	AFTER_DOCTYPE_PUBLIC_KEYWORD;
	BEFORE_DOCTYPE_PUBLIC_IDENTIFIER;
	DOCTYPE_PUBLIC_IDENTIFIER( q : Quotation ); // DOUBLE_QUOTED & SINGLE_QUOTED
	AFTER_DOCTYPE_PUBLIC_IDENTIFIER;
	BETWEEN_DOCTYPE_PUBLIC_AND_SYSTEM_IDENTIFIERS;
	AFTER_DOCTYPE_SYSTEM_KEYWORD;
	BEFORE_DOCTYPE_SYSTEM_IDENTIFIER;
	DOCTYPE_SYSTEM_IDENTIFIER( q : Quotation ); // DOUBLE_QUOTED & SINGLE_QUOTED
	AFTER_DOCTYPE_SYSTEM_IDENTIFIER;
	BOGUS_DOCTYPE;
	CDATA_SECTION;
}